import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Roboto_Mono } from "next/font/google"
const roboto = Roboto_Mono({subsets:['vietnamese']})
// app/layout.tsx
export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={roboto.className}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
