import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// app/layout.tsx
export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
       <ToastContainer />
    </html>
  );
}
